[NankaiMathUndergradNews]
title = "南开大学数学学院本科生教育消息"
url = "https://math.nankai.edu.cn/"
entrySelector = "#container-2 .mod2 .ml .post-23 .news_list li.news"
titleSelector = ".news_title a"
linkSelector = ".news_title a"

[NankaiJWCNotices]
title = "南开大学教务处通知"
url = "https://jwc.nankai.edu.cn/"
entrySelector = ".section1-list .item a"
titleSelector = ".con:nth-of-type(2)"
linkSelector = ".con:nth-of-type(1)"
