[NankaiMathUndergradNews]
title = "南开大学数学学院消息-本科生"
url = "https://math.nankai.edu.cn/"
entrySelector = "#container-2 .news_list li.news div.news_box.clearfix"
titleSelector = ".news_title a:nth-of-type(2)"
linkSelector = ".news_title a:nth-of-type(2)"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
