[NankaiMathUndergradNews]
title = "南开大学数学学院本科生教育消息"
url = "https://math.nankai.edu.cn/"
entrySelector = "#container-2 .mod2 .ml .post-23 .news_list li.news"
titleSelector = ".news_title a:nth-of-type(2)"
linkSelector = ".news_title a"

[NankaiJWCNotices]
title = "南开大学教务处通知"
url = "https://jwc.nankai.edu.cn/"
entrySelector = ".section1-list .item a"
titleSelector = ".con:nth-of-type(2)"
linkSelector = ".con:nth-of-type(1)"

[ChernInstituteAcademicNews]
title = "陈省身数学研究所 学术动态"
url = "http://www.nim.nankai.edu.cn/xsbg/list.htm"
entrySelector = ".col_news_list .wp_article_list .list_item"
titleSelector = ".fields.pr_fields span:nth-of-type(2)"
linkSelector = ".fields.pr_fields span:nth-of-type(2)"

[ChernInstituteAcademicConferences]
title = "陈省身数学研究所 学术会议"
url = "http://www.nim.nankai.edu.cn/xshy/list.htm"
entrySelector = ".col_news_list .wp_article_list .list_item"
titleSelector = ".Article_Title a"
linkSelector = ".Article_Title a"

[ClayMathEvent]
title = "Clay Mathematics Institute Events"
url = "https://www.claymath.org/events/"
entrySelector = "a.tile"
titleSelector = "h3"
linkSelector = "div[class*='tile-link']"

[CRMathActivities]
title = "Centre de recherches mathématiques Activities"
url = "https://www.crmath.ca/en/activities/"
entrySelector = "div.col1, div.col2"
titleSelector = "h3.title"
linkSelector = ""

[MathInstituteEvents]
title = "Mathematical Sciences Institutes Events"
url = "https://mathinstitutes.org/events"
entrySelector = "div[class*='card']"
titleSelector = "a"
linkSelector = "a"

[IHESSeminars]
title = "IHES Seminars"
url = "https://www.ihes.fr/en/events/#seminars"
entrySelector = "td.Agenda-date, td.Agenda-sujet"
titleSelector = "a"
linkSelector = "a"

[IHESConferences]
title = "IHES Seminars"
url = "https://www.ihes.fr/en/events/#conferences"
entrySelector = "td.Agenda-date, td.Agenda-sujet"
titleSelector = "a"
linkSelector = "a"

[SWCAWS]
title = "The Southwest Center for Arithmetic Geometry Arizona Winter Schools"
url = "https://swc-math.github.io/aws/"
entrySelector = "li"
titleSelector = "a"
linkSelector = "a"

[BICMRSeminarsAndColloquium]
title = "BICMR Seminars and Colloquium"
url = "https://bicmr.pku.edu.cn/"
entrySelector = ".mainpart .container > .cont-l:nth-of-type(1) dl.event-lst"
titleSelector = "dd p.black a"
linkSelector = "dd p.black a"

[BICMRConferenceAndMiniCourse]
title = "BICMR Conference and Mini-Course"
url = "https://bicmr.pku.edu.cn/"
entrySelector = ".mainpart .container > .cont-l:nth-of-type(2) dl.event-lst"
titleSelector = "dd p.black a"
linkSelector = "dd p.black a"

[YMSCSeminars]
title = "YMSC Seminars"
url = "https://ymsc.tsinghua.edu.cn/en/"
entrySelector = ".main_box > .tzxs:nth-of-type(1) .tzxs_left .box.fix_ksd ul.list-data-wrap li.item"
titleSelector = "a.right.text .t-1"
linkSelector = "a.right.text"

[YMSCLectures]
title = "YMSC Lectures"
url = "https://ymsc.tsinghua.edu.cn/en/"
entrySelector = ".main_box > .tzxs:nth-of-type(1) .tzxs_left .box.fix_sx ul.list-data-wrap li.item"
titleSelector = "a.right.text .t-1"
linkSelector = "a.right.text"

[YMSCConferences]
title = "YMSC Conferences"
url = "https://ymsc.tsinghua.edu.cn/en/"
entrySelector = ".main_box > .tzxs:nth-of-type(2) .tzxs_right .box.fix_ksd ul.list-data-wrap li.item"
titleSelector = "a.right.text .t-1"
linkSelector = "a.right.text"
