[ClayMathEvent]
title = "Clay Mathematics Institute Events"
url = "https://www.claymath.org/events/"
entrySelector = "a.tile"
titleSelector = "h3"
linkSelector = "div[class*='tile-link']"

[CRMathActivities]
title = "Centre de recherches mathématiques Activities"
url = "https://www.crmath.ca/en/activities/"
entrySelector = "div.col1, div.col2"
titleSelector = "h3.title"
linkSelector = ""

[MathInstituteEvents]
title = "Mathematical Sciences Institutes Events"
url = "https://mathinstitutes.org/events"
entrySelector = "div[class*='card']"
titleSelector = "a"
linkSelector = "a"

[IHESSeminars]
title = "IHES Seminars"
url = "https://www.ihes.fr/en/events/#seminars"
entrySelector = "tr:has(td.Agenda-sujet)"
titleSelector = "td.Agenda-sujet a"
linkSelector = "td.Agenda-sujet a"

[IHESConferences]
title = "IHES Seminars"
url = "https://www.ihes.fr/en/events/#conferences"
entrySelector = "tr:has(td.Agenda-sujet)"
titleSelector = "td.Agenda-sujet a"
linkSelector = "td.Agenda-sujet a"

[SWCAWS]
title = "The Southwest Center for Arithmetic Geometry Arizona Winter Schools"
url = "https://swc-math.github.io/aws/"
entrySelector = "li"
titleSelector = "a"
linkSelector = "a"

[BICMRSeminarsAndColloquium]
title = "BICMR Seminars and Colloquium"
url = "https://bicmr.pku.edu.cn/"
entrySelector = ".mainpart .container > .cont-l:nth-of-type(1) dl.event-lst"
titleSelector = "dd p.black a"
linkSelector = "dd p.black a"

[BICMRConferenceAndMiniCourse]
title = "BICMR Conference and Mini-Course"
url = "https://bicmr.pku.edu.cn/"
entrySelector = ".mainpart .container > .cont-l:nth-of-type(2) dl.event-lst"
titleSelector = "dd p.black a"
linkSelector = "dd p.black a"

[YMSCSeminars]
title = "YMSC Seminars"
url = "https://ymsc.tsinghua.edu.cn/en/"
entrySelector = ".main_box > .tzxs:nth-of-type(1) .tzxs_left .box.fix_ksd ul.list-data-wrap li.item"
titleSelector = "a.right.text .t-1"
linkSelector = "a.right.text"

[YMSCLectures]
title = "YMSC Lectures"
url = "https://ymsc.tsinghua.edu.cn/en/"
entrySelector = ".main_box > .tzxs:nth-of-type(1) .tzxs_left .box.fix_sx ul.list-data-wrap li.item"
titleSelector = "a.right.text .t-1"
linkSelector = "a.right.text"

[YMSCConferences]
title = "YMSC Conferences"
url = "https://ymsc.tsinghua.edu.cn/en/"
entrySelector = ".main_box > .tzxs:nth-of-type(2) .tzxs_right .box.fix_ksd ul.list-data-wrap li.item"
titleSelector = "a.right.text .t-1"
linkSelector = "a.right.text"

[ResearchSeminars]
title = "researchseminars.org"
url = "https://researchseminars.org/"
entrySelector = "tr.talk:not(.lasttime)"
titleSelector = "td.talktitle a"
linkSelector = "td.seriesname a"
