[NankaiMathSchoolNews]
title = "南开大学数学学院消息"
url = "https://math.nankai.edu.cn/"
entrySelector = "body > div#container-2.wrapper.main2.showdiv:nth-child(5) > div.inner > div.mod.mod2.clearfix:nth-child(2) > div.ml:nth-child(1) > div.post.post2.post-23.mbox"
titleSelector = "body > div#container-2.wrapper.main2.showdiv:nth-child(5) > div.inner > div.mod.mod2.clearfix:nth-child(2) > div.ml:nth-child(1) > div.post.post2.post-23.mbox > div.con.news_tu:nth-child(2) > ul.news_list.clearfix > li.news > div.news_box.clearfix > div.news_wz:nth-child(2) > div.news_con > div.news_title > a"
linkSelector = ""

[NankaiJWCNotices]
title = "南开大学教务处通知"
url = "https://jwc.nankai.edu.cn/"
entrySelector = ".section1-list .item a"
titleSelector = ".con:nth-of-type(2)"
linkSelector = ".con:nth-of-type(1)"
